package com.hireconnect.entity;

import jakarta.persistence.*;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "payroll_history")
public class PayrollHistory {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "user_id", nullable = false)
    private Long userId;
    
    @Column(name="userName", nullable = false)
    private String userName;

    @Column(name = "payroll_month")
    private LocalDate payrollMonth;

    @Column(name = "gross_salary", precision = 10, scale = 2)
    private BigDecimal grossSalary;

    @Column(name = "basic_salary", precision = 10, scale = 2)
    private BigDecimal basicSalary;

    @Column(name = "da", precision = 10, scale = 2)
    private BigDecimal da;

    @Column(precision = 10, scale = 2)
    private BigDecimal hra;

    @Column(name = "conveyance_allowance", precision = 10, scale = 2)
    private BigDecimal conveyanceAllowance;

    @Column(name = "medical_allowance", precision = 10, scale = 2)
    private BigDecimal medicalAllowance;

    @Column(precision = 10, scale = 2)
    private BigDecimal lta;

    @Column(name = "other_allowances", precision = 10, scale = 2)
    private BigDecimal otherAllowances;

    @Column(name = "special_allowance", precision = 10, scale = 2)
    private BigDecimal specialAllowance;

    @Column(name = "total_earnings", precision = 10, scale = 2)
    private BigDecimal totalEarnings;

    @Column(name = "pf_employee", precision = 10, scale = 2)
    private BigDecimal pfEmployee;

    @Column(name = "professional_tax", precision = 10, scale = 2)
    private BigDecimal professionalTax;

    @Column(name = "tax_deductions", precision = 10, scale = 2)
    private BigDecimal taxDeductions;

    @Column(name = "other_deductions", precision = 10, scale = 2)
    private BigDecimal otherDeductions;

    @Column(name = "esic", precision = 10, scale = 2)
    private BigDecimal esic;

    @Column(name = "medical_insurance", precision = 10, scale = 2)
    private BigDecimal medicalInsurance;

    @Column(name = "total_deductions", precision = 10, scale = 2)
    private BigDecimal totalDeductions;

    @Column(name = "net_salary", precision = 10, scale = 2)
    private BigDecimal netSalary;

    @Column(name = "lop_days")
    private Integer lopDays;

    @Column(name = "overtime_hours")
    private Integer overtimeHours;

    @Enumerated(EnumType.STRING)
    private PayrollStatus status = PayrollStatus.PENDING;

    @Column(name = "payment_date")
    private LocalDate paymentDate;

    @Column(name = "payslip_generated")
    private Boolean payslipGenerated = false;

    @Column(name = "payslip_path")
    private String payslipPath;

    @Column(name = "payslip_content_type")
    private String payslipContentType;

    @JsonIgnore
    @Lob
    @Column(name = "payslip_data", columnDefinition = "LONGBLOB")
    private byte[] payslipData;

    @Column(name = "created_by")
    private Long createdBy;

    @Column(name = "auto_generated")
    private Boolean autoGenerated = false;

    @Column(name = "entry_type", length = 20)
    private String entryType = "manual";

    @Column(columnDefinition = "TEXT")
    private String remarks;

    @Column(name = "salary_components_json", columnDefinition = "LONGTEXT")
    private String salaryComponentsJson;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    public enum PayrollStatus {
        PENDING, APPROVED, PAID, CANCELLED
    }

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

    public LocalDate getPayrollMonth() {
        return payrollMonth;
    }

    public void setPayrollMonth(LocalDate payrollMonth) {
        this.payrollMonth = payrollMonth;
    }

    public BigDecimal getGrossSalary() {
        return grossSalary;
    }

    public void setGrossSalary(BigDecimal grossSalary) {
        this.grossSalary = grossSalary;
    }

    public BigDecimal getBasicSalary() {
        return basicSalary;
    }

    public void setBasicSalary(BigDecimal basicSalary) {
        this.basicSalary = basicSalary;
    }

    public BigDecimal getDa() {
        return da;
    }

    public void setDa(BigDecimal da) {
        this.da = da;
    }

    public BigDecimal getHra() {
        return hra;
    }

	public void setHra(BigDecimal hra) {
		this.hra = hra;
	}

	public BigDecimal getConveyanceAllowance() {
		return conveyanceAllowance;
	}

	public void setConveyanceAllowance(BigDecimal conveyanceAllowance) {
		this.conveyanceAllowance = conveyanceAllowance;
	}

	public BigDecimal getMedicalAllowance() {
		return medicalAllowance;
	}

	public void setMedicalAllowance(BigDecimal medicalAllowance) {
		this.medicalAllowance = medicalAllowance;
	}

	public BigDecimal getLta() {
		return lta;
	}

	public void setLta(BigDecimal lta) {
		this.lta = lta;
	}

    public BigDecimal getOtherAllowances() {
        return otherAllowances;
    }

    public void setOtherAllowances(BigDecimal otherAllowances) {
        this.otherAllowances = otherAllowances;
    }

    public BigDecimal getSpecialAllowance() {
        return specialAllowance;
    }

    public void setSpecialAllowance(BigDecimal specialAllowance) {
        this.specialAllowance = specialAllowance;
    }

	public BigDecimal getTotalEarnings() {
		return totalEarnings;
	}

	public void setTotalEarnings(BigDecimal totalEarnings) {
		this.totalEarnings = totalEarnings;
	}

	public BigDecimal getPfEmployee() {
		return pfEmployee;
	}

	public void setPfEmployee(BigDecimal pfEmployee) {
		this.pfEmployee = pfEmployee;
	}

	public BigDecimal getProfessionalTax() {
		return professionalTax;
	}

	public void setProfessionalTax(BigDecimal professionalTax) {
		this.professionalTax = professionalTax;
	}

	public BigDecimal getTaxDeductions() {
		return taxDeductions;
	}

	public void setTaxDeductions(BigDecimal taxDeductions) {
		this.taxDeductions = taxDeductions;
	}

    public BigDecimal getOtherDeductions() {
        return otherDeductions;
    }

    public void setOtherDeductions(BigDecimal otherDeductions) {
        this.otherDeductions = otherDeductions;
    }

    public BigDecimal getEsic() {
        return esic;
    }

    public void setEsic(BigDecimal esic) {
        this.esic = esic;
    }

    public BigDecimal getMedicalInsurance() {
        return medicalInsurance;
    }

    public void setMedicalInsurance(BigDecimal medicalInsurance) {
        this.medicalInsurance = medicalInsurance;
    }

    public BigDecimal getTotalDeductions() {
        return totalDeductions;
    }

	public void setTotalDeductions(BigDecimal totalDeductions) {
		this.totalDeductions = totalDeductions;
	}

	public BigDecimal getNetSalary() {
		return netSalary;
	}

	public void setNetSalary(BigDecimal netSalary) {
		this.netSalary = netSalary;
	}

	public Integer getLopDays() {
		return lopDays;
	}

	public void setLopDays(Integer lopDays) {
		this.lopDays = lopDays;
	}

	public Integer getOvertimeHours() {
		return overtimeHours;
	}

	public void setOvertimeHours(Integer overtimeHours) {
		this.overtimeHours = overtimeHours;
	}

	public PayrollStatus getStatus() {
		return status;
	}

	public void setStatus(PayrollStatus status) {
		this.status = status;
	}

	public LocalDate getPaymentDate() {
		return paymentDate;
	}

	public void setPaymentDate(LocalDate paymentDate) {
		this.paymentDate = paymentDate;
	}

	public Boolean getPayslipGenerated() {
		return payslipGenerated;
	}

	public void setPayslipGenerated(Boolean payslipGenerated) {
		this.payslipGenerated = payslipGenerated;
	}

	public String getPayslipPath() {
		return payslipPath;
	}

	public void setPayslipPath(String payslipPath) {
		this.payslipPath = payslipPath;
	}

    public String getPayslipContentType() {
        return payslipContentType;
    }

    public void setPayslipContentType(String payslipContentType) {
        this.payslipContentType = payslipContentType;
    }

    public byte[] getPayslipData() {
        return payslipData;
    }

    public void setPayslipData(byte[] payslipData) {
        this.payslipData = payslipData;
    }

	public Long getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

    public Boolean getAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public String getEntryType() {
        return entryType == null ? "manual" : entryType;
    }

    public void setEntryType(String entryType) {
        this.entryType = entryType;
    }

    public String getRemarks() {
        return remarks;
    }

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

    public String getSalaryComponentsJson() {
        return salaryComponentsJson;
    }

    public void setSalaryComponentsJson(String salaryComponentsJson) {
        this.salaryComponentsJson = salaryComponentsJson;
    }

	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @PrePersist
    private void ensureEntryType() {
        if (entryType == null || entryType.isBlank()) {
            entryType = "manual";
        }
    }
    
}
