package com.hireconnect.dto.request;

import lombok.Data;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

@Data
public class PayrollRequest {
    private Long userId;
    @JsonProperty("username")
    private String userName;
    private LocalDate payrollMonth;
    private BigDecimal grossSalary;
    private BigDecimal basicSalary;
    private BigDecimal da;
    private BigDecimal hra;
    private BigDecimal conveyanceAllowance;
    private BigDecimal medicalAllowance;
    private BigDecimal lta;
    private BigDecimal otherAllowances;
    private BigDecimal specialAllowance;
    private BigDecimal totalEarnings;
    private BigDecimal pfEmployee;
    private BigDecimal professionalTax;
    private BigDecimal taxDeductions;
    private BigDecimal otherDeductions;
    private BigDecimal esic;
    private BigDecimal medicalInsurance;
    private BigDecimal totalDeductions;
    private BigDecimal netSalary;
    private Integer lopDays;
    private Integer overtimeHours;
    private String notes;
    private Boolean autoGenerated;
    private String entryType;
    private List<SalaryComponentValue> salaryComponents = new ArrayList<>();
	public Long getUserId() {
		return userId;
	}
	public void setUserId(Long userId) {
		this.userId = userId;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public LocalDate getPayrollMonth() {
		return payrollMonth;
	}
	public void setPayrollMonth(LocalDate payrollMonth) {
		this.payrollMonth = payrollMonth;
	}
	public BigDecimal getGrossSalary() {
		return grossSalary;
	}
	public void setGrossSalary(BigDecimal grossSalary) {
		this.grossSalary = grossSalary;
	}
	public BigDecimal getBasicSalary() {
		return basicSalary;
	}
	public void setBasicSalary(BigDecimal basicSalary) {
		this.basicSalary = basicSalary;
	}
	public BigDecimal getDa() {
		return da;
	}
	public void setDa(BigDecimal da) {
		this.da = da;
	}
	public BigDecimal getHra() {
		return hra;
	}
	public void setHra(BigDecimal hra) {
		this.hra = hra;
	}
	public BigDecimal getConveyanceAllowance() {
		return conveyanceAllowance;
	}
	public void setConveyanceAllowance(BigDecimal conveyanceAllowance) {
		this.conveyanceAllowance = conveyanceAllowance;
	}
	public BigDecimal getMedicalAllowance() {
		return medicalAllowance;
	}
	public void setMedicalAllowance(BigDecimal medicalAllowance) {
		this.medicalAllowance = medicalAllowance;
	}
	public BigDecimal getLta() {
		return lta;
	}
	public void setLta(BigDecimal lta) {
		this.lta = lta;
	}
	public BigDecimal getOtherAllowances() {
		return otherAllowances;
	}
	public void setOtherAllowances(BigDecimal otherAllowances) {
		this.otherAllowances = otherAllowances;
	}
	public BigDecimal getSpecialAllowance() {
		return specialAllowance;
	}
	public void setSpecialAllowance(BigDecimal specialAllowance) {
		this.specialAllowance = specialAllowance;
	}
	public BigDecimal getTotalEarnings() {
		return totalEarnings;
	}
	public void setTotalEarnings(BigDecimal totalEarnings) {
		this.totalEarnings = totalEarnings;
	}
	public BigDecimal getPfEmployee() {
		return pfEmployee;
	}
	public void setPfEmployee(BigDecimal pfEmployee) {
		this.pfEmployee = pfEmployee;
	}
	public BigDecimal getProfessionalTax() {
		return professionalTax;
	}
	public void setProfessionalTax(BigDecimal professionalTax) {
		this.professionalTax = professionalTax;
	}
	public BigDecimal getTaxDeductions() {
		return taxDeductions;
	}
	public void setTaxDeductions(BigDecimal taxDeductions) {
		this.taxDeductions = taxDeductions;
	}
	public BigDecimal getOtherDeductions() {
		return otherDeductions;
	}
	public void setOtherDeductions(BigDecimal otherDeductions) {
		this.otherDeductions = otherDeductions;
	}
	public BigDecimal getEsic() {
		return esic;
	}
	public void setEsic(BigDecimal esic) {
		this.esic = esic;
	}
	public BigDecimal getMedicalInsurance() {
		return medicalInsurance;
	}
	public void setMedicalInsurance(BigDecimal medicalInsurance) {
		this.medicalInsurance = medicalInsurance;
	}
	public BigDecimal getTotalDeductions() {
		return totalDeductions;
	}
	public void setTotalDeductions(BigDecimal totalDeductions) {
		this.totalDeductions = totalDeductions;
	}
	public BigDecimal getNetSalary() {
		return netSalary;
	}
	public void setNetSalary(BigDecimal netSalary) {
		this.netSalary = netSalary;
	}
	public Integer getLopDays() {
		return lopDays;
	}
	public void setLopDays(Integer lopDays) {
		this.lopDays = lopDays;
	}
	public Integer getOvertimeHours() {
		return overtimeHours;
	}
	public void setOvertimeHours(Integer overtimeHours) {
		this.overtimeHours = overtimeHours;
	}
	public String getNotes() {
		return notes;
	}
	public void setNotes(String notes) {
		this.notes = notes;
	}
	public Boolean getAutoGenerated() {
		return autoGenerated;
	}
	public void setAutoGenerated(Boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}
	public String getEntryType() {
		return entryType;
	}
	public void setEntryType(String entryType) {
		this.entryType = entryType;
	}
	public List<SalaryComponentValue> getSalaryComponents() {
		return salaryComponents;
	}
	public void setSalaryComponents(List<SalaryComponentValue> salaryComponents) {
		this.salaryComponents = salaryComponents;
	}

    public static class SalaryComponentValue {
        private String componentName;
        private String valueType;
        private BigDecimal value;

        public String getComponentName() {
            return componentName;
        }

        public void setComponentName(String componentName) {
            this.componentName = componentName;
        }

        public String getValueType() {
            return valueType;
        }

        public void setValueType(String valueType) {
            this.valueType = valueType;
        }

        public BigDecimal getValue() {
            return value;
        }

        public void setValue(BigDecimal value) {
            this.value = value;
        }
    }
	    
}