package com.hireconnect.service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.Resource;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.hireconnect.dto.request.PayrollRequest;
import com.hireconnect.dto.response.PayrollResponse;
import com.hireconnect.entity.PayrollHistory;
import com.hireconnect.entity.User;
import com.hireconnect.repository.PayrollHistoryRepository;
import com.hireconnect.repository.UserRepository;
import com.hireconnect.util.FileStorageUtil;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

@Service
public class PayrollService {

    @Autowired
    private PayrollHistoryRepository payrollHistoryRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private ObjectMapper objectMapper;

    private PayrollResponse enrichPayrollWithUserDetails(PayrollHistory payroll) {
        PayrollResponse dto = new PayrollResponse();

        dto.setId(payroll.getId());
        dto.setUserId(payroll.getUserId());
        dto.setUserName(payroll.getUserName());
        dto.setPayrollMonth(payroll.getPayrollMonth());
        dto.setGrossSalary(payroll.getGrossSalary());
        dto.setBasicSalary(payroll.getBasicSalary());
        dto.setDa(payroll.getDa());
        dto.setHra(payroll.getHra());
        dto.setConveyanceAllowance(payroll.getConveyanceAllowance());
        dto.setMedicalAllowance(payroll.getMedicalAllowance());
        dto.setLta(payroll.getLta());
        dto.setOtherAllowances(payroll.getOtherAllowances());
        dto.setSpecialAllowance(payroll.getSpecialAllowance());
        dto.setTotalEarnings(payroll.getTotalEarnings());
        dto.setPfEmployee(payroll.getPfEmployee());
        dto.setProfessionalTax(payroll.getProfessionalTax());
        dto.setTaxDeductions(payroll.getTaxDeductions());
        dto.setOtherDeductions(payroll.getOtherDeductions());
        dto.setEsic(payroll.getEsic());
        dto.setMedicalInsurance(payroll.getMedicalInsurance());
        dto.setTotalDeductions(payroll.getTotalDeductions());
        dto.setNetSalary(payroll.getNetSalary());
        dto.setLopDays(payroll.getLopDays());
        dto.setOvertimeHours(payroll.getOvertimeHours());
        dto.setStatus(payroll.getStatus());
        dto.setPaymentDate(payroll.getPaymentDate());
        dto.setPayslipGenerated(payroll.getPayslipGenerated());
        dto.setPayslipPath(payroll.getPayslipPath());
        dto.setAutoGenerated(payroll.getAutoGenerated());
        dto.setEntryType(payroll.getEntryType());
        dto.setRemarks(payroll.getRemarks());
        dto.setCreatedAt(payroll.getCreatedAt());
        dto.setSalaryComponents(parseSalaryComponents(payroll.getSalaryComponentsJson()));

        try {
            User user = userRepository.findById(payroll.getUserId()).orElse(null);
            if (user != null) {
                dto.setEmployeeId(user.getEmployeeId() != null ? user.getEmployeeId() : "EMP-" + user.getId());
                dto.setEmployeeName(user.getFullName());
                dto.setJoiningDate(user.getCreatedAt());

                if (Boolean.TRUE.equals(payroll.getAutoGenerated())) {
                    dto.setSource("Auto Generated");
                } else if ("auto".equalsIgnoreCase(payroll.getEntryType())) {
                    dto.setSource("Auto Entry");
                } else {
                    dto.setSource("Manual Entry");
                }

                if (payroll.getPayrollMonth() != null) {
                    dto.setPayPeriod(payroll.getPayrollMonth().format(DateTimeFormatter.ofPattern("MMMM yyyy")));
                    dto.setPayDate(payroll.getPayrollMonth().format(DateTimeFormatter.ofPattern("dd MMM yyyy")));
                }
            } else {
                dto.setEmployeeId("N/A");
                dto.setEmployeeName(payroll.getUserName() != null ? payroll.getUserName() : "Unknown");
                dto.setJoiningDate(null);
            }
        } catch (Exception e) {
            dto.setEmployeeId("N/A");
            dto.setEmployeeName(payroll.getUserName() != null ? payroll.getUserName() : "Unknown");
            dto.setJoiningDate(null);
        }

        return dto;
    }

    public List<PayrollResponse> getAllPayrolls() {
        return payrollHistoryRepository.findAll()
                .stream()
                .map(this::enrichPayrollWithUserDetails)
                .collect(Collectors.toList());
    }

    public List<PayrollResponse> getAllPayrollsByCompany(Long companyId) {
        if (companyId == null) {
            throw new RuntimeException("companyId is required");
        }
        return payrollHistoryRepository.findAllByCompanyIdOrderByPayrollMonthDesc(companyId)
                .stream()
                .map(this::enrichPayrollWithUserDetails)
                .collect(Collectors.toList());
    }

    public PayrollResponse getPayrollById(Long id) {
        PayrollHistory payroll = payrollHistoryRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + id));
        return enrichPayrollWithUserDetails(payroll);
    }

    public PayrollResponse getPayrollById(Long id, Long companyId) {
        if (companyId == null) {
            throw new RuntimeException("companyId is required");
        }
        PayrollHistory payroll = payrollHistoryRepository.findByIdAndCompanyId(id, companyId)
                .orElseThrow(() -> new RuntimeException("Payroll not found for this company"));
        return enrichPayrollWithUserDetails(payroll);
    }

    public List<PayrollResponse> getPayrollByUser(Long userId) {
        return payrollHistoryRepository.findByUserIdOrderByPayrollMonthDesc(userId)
                .stream()
                .map(this::enrichPayrollWithUserDetails)
                .collect(Collectors.toList());
    }

    public List<PayrollResponse> getPayrollByUser(Long userId, Long companyId) {
        if (companyId == null) {
            throw new RuntimeException("companyId is required");
        }
        return payrollHistoryRepository.findByUserIdAndCompanyIdOrderByPayrollMonthDesc(userId, companyId)
                .stream()
                .map(this::enrichPayrollWithUserDetails)
                .collect(Collectors.toList());
    }

    @Transactional
    public PayrollHistory createPayroll(PayrollRequest request) {
        if (request.getPayrollMonth() != null && request.getUserId() != null) {
            payrollHistoryRepository.findByUserIdAndMonth(request.getUserId(), request.getPayrollMonth())
                    .ifPresent(existing -> {
                        throw new RuntimeException("Payroll already exists for this month");
                    });
        }

        PayrollHistory payroll = new PayrollHistory();
        mapRequestToEntity(request, payroll);

        return payrollHistoryRepository.save(payroll);
    }

    @Transactional
    public PayrollHistory updatePayroll(Long id, PayrollRequest request) {
        PayrollHistory payroll = payrollHistoryRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + id));
        mapRequestToEntity(request, payroll);

        return payrollHistoryRepository.save(payroll);
    }

    @Transactional
    public void deletePayroll(Long id) {
        PayrollHistory payroll = payrollHistoryRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + id));
        payrollHistoryRepository.delete(payroll);
    }

    @Transactional
    public PayrollHistory generateAutoPayroll(PayrollRequest request) {
        return createPayroll(request);
    }

    @Transactional
    public PayrollHistory manualPayrollEntry(PayrollRequest request) {
        request.setEntryType("manual");
        return createPayroll(request);
    }

    @Transactional
    public PayrollHistory autoPayrollEntry(PayrollRequest request) {
        request.setEntryType("auto");
        return createPayroll(request);
    }

    public Map<String, Object> getAnalytics(String range) {
        Map<String, Object> analytics = new HashMap<>();

        long totalEmployees = userRepository.countByRole(User.Role.EMPLOYEE);
        analytics.put("totalEmployees", totalEmployees);

        LocalDate now = LocalDate.now();
        LocalDate currentMonth = LocalDate.of(now.getYear(), now.getMonth(), 1);
        List<PayrollHistory> currentMonthPayrolls = payrollHistoryRepository.findByYearAndMonth(
                currentMonth.getYear(),
                currentMonth.getMonthValue()
        );
        analytics.put("activePayrolls", currentMonthPayrolls.size());

        BigDecimal totalPayouts = currentMonthPayrolls.stream()
                .map(PayrollHistory::getTotalEarnings)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        analytics.put("totalPayouts", totalPayouts);
        analytics.put("pendingReimbursements", 0);

        return analytics;
    }

    public ResponseEntity<?> exportPayrolls(String format, String status, String month) {
        List<PayrollHistory> payrolls;

        if (!"all".equals(status)) {
            payrolls = payrollHistoryRepository.findByStatus(
                    PayrollHistory.PayrollStatus.valueOf(status.toUpperCase())
            );
        } else {
            payrolls = payrollHistoryRepository.findAll();
        }

        return ResponseEntity.ok(Map.of(
                "message", "Export functionality to be implemented",
                "format", format,
                "status", status,
                "month", month,
                "totalRecords", payrolls.size()
        ));
    }

    @Transactional
    public Map<String, Object> generatePayslip(Long payrollId) throws IOException, DocumentException {
        PayrollHistory payroll = payrollHistoryRepository.findById(payrollId)
                .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + payrollId));
        User user = userRepository.findById(payroll.getUserId())
                .orElseThrow(() -> new RuntimeException("User not found"));

        byte[] payslipBytes = generatePayslipPdf(payroll, user);

        payroll.setPayslipGenerated(true);
        payroll.setPayslipContentType(MediaType.APPLICATION_PDF_VALUE);
        payroll.setPayslipData(payslipBytes);
        payroll.setPayslipPath("/api/payroll/" + payroll.getId() + "/download-payslip");
        payrollHistoryRepository.save(payroll);

        Map<String, Object> result = new HashMap<>();
        result.put("message", "Payslip generated successfully");
        result.put("filePath", payroll.getPayslipPath());
        return result;
    }

    public ResponseEntity<Resource> downloadPayslip(Long payrollId) {
        return buildPayslipFileResponse(payrollId, true);
    }

    public ResponseEntity<Resource> previewPayslip(Long payrollId) {
        return buildPayslipFileResponse(payrollId, false);
    }

    private ResponseEntity<Resource> buildPayslipFileResponse(Long payrollId, boolean attachment) {
        PayrollHistory payroll = payrollHistoryRepository.findById(payrollId)
                .orElseThrow(() -> new RuntimeException("Payroll not found with id: " + payrollId));

        if (!payroll.getPayslipGenerated() || payroll.getPayslipPath() == null) {
            throw new RuntimeException("Payslip not generated yet");
        }

        return FileStorageUtil.buildResponse(
                payroll.getPayslipData(),
                buildLegacyPayslipPath(payroll.getPayslipPath()),
                payroll.getPayslipContentType(),
                buildPayslipFileName(payroll),
                attachment
        );
    }

    private void mapRequestToEntity(PayrollRequest request, PayrollHistory payroll) {
        payroll.setUserId(request.getUserId());
        payroll.setUserName(request.getUserName());
        payroll.setPayrollMonth(request.getPayrollMonth());
        payroll.setGrossSalary(request.getGrossSalary());
        payroll.setBasicSalary(request.getBasicSalary());
        payroll.setDa(request.getDa());
        payroll.setHra(request.getHra());
        payroll.setConveyanceAllowance(request.getConveyanceAllowance());
        payroll.setMedicalAllowance(request.getMedicalAllowance());
        payroll.setLta(request.getLta());
        payroll.setOtherAllowances(request.getOtherAllowances());
        payroll.setSpecialAllowance(request.getSpecialAllowance());
        payroll.setPfEmployee(request.getPfEmployee());
        payroll.setProfessionalTax(request.getProfessionalTax());
        payroll.setTaxDeductions(request.getTaxDeductions());
        payroll.setOtherDeductions(request.getOtherDeductions());
        payroll.setEsic(request.getEsic());
        payroll.setMedicalInsurance(request.getMedicalInsurance());
        payroll.setLopDays(request.getLopDays());
        payroll.setOvertimeHours(request.getOvertimeHours());
        payroll.setAutoGenerated(request.getAutoGenerated());
        payroll.setEntryType(request.getEntryType());
        payroll.setTotalEarnings(request.getTotalEarnings());
        payroll.setTotalDeductions(request.getTotalDeductions());
        payroll.setNetSalary(request.getNetSalary());
        try {
            payroll.setSalaryComponentsJson(
                    objectMapper.writeValueAsString(
                            request.getSalaryComponents() == null ? List.of() : request.getSalaryComponents()
                    )
            );
        } catch (Exception e) {
            throw new RuntimeException("Invalid salaryComponents payload");
        }
    }

    private List<Map<String, Object>> parseSalaryComponents(String salaryComponentsJson) {
        if (salaryComponentsJson == null || salaryComponentsJson.isBlank()) {
            return List.of();
        }
        try {
            return objectMapper.readValue(
                    salaryComponentsJson,
                    new TypeReference<List<Map<String, Object>>>() {}
            );
        } catch (Exception e) {
            return List.of();
        }
    }

    private byte[] generatePayslipPdf(PayrollHistory payroll, User user) throws IOException, DocumentException {
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        Document document = new Document();
        PdfWriter.getInstance(document, outputStream);
        document.open();

        Font titleFont = new Font(Font.FontFamily.HELVETICA, 18, Font.BOLD);
        Paragraph title = new Paragraph("PAYSLIP", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        document.add(new Paragraph("\n"));

        String employeeId = user.getEmployeeId() != null ? user.getEmployeeId() : "EMP-" + user.getId();
        document.add(new Paragraph("Employee Name: " + user.getFullName()));
        document.add(new Paragraph("Employee ID: " + employeeId));
        document.add(new Paragraph("Joining Date: " + (
                user.getCreatedAt() != null
                        ? user.getCreatedAt().format(DateTimeFormatter.ofPattern("dd MMM yyyy"))
                        : "N/A"
        )));
        document.add(new Paragraph("Month: " + payroll.getPayrollMonth().format(
                DateTimeFormatter.ofPattern("MMMM yyyy"))));

        document.add(new Paragraph("\n"));

        Font boldFont = new Font(Font.FontFamily.HELVETICA, 12, Font.BOLD);

        PdfPTable earningsTable = new PdfPTable(2);
        earningsTable.setWidthPercentage(100);

        addTableHeader(earningsTable, "EARNINGS", boldFont);
        addTableRow(earningsTable, "Basic Salary", payroll.getBasicSalary());
        addTableRow(earningsTable, "HRA", payroll.getHra());
        addTableRow(earningsTable, "Conveyance", payroll.getConveyanceAllowance());
        addTableRow(earningsTable, "Medical", payroll.getMedicalAllowance());
        addTableRow(earningsTable, "LTA", payroll.getLta());
        addTableRow(earningsTable, "Other Allowances", payroll.getOtherAllowances());
        addTableRow(earningsTable, "Total Earnings", payroll.getTotalEarnings(), boldFont);

        document.add(earningsTable);
        document.add(new Paragraph("\n"));

        PdfPTable deductionsTable = new PdfPTable(2);
        deductionsTable.setWidthPercentage(100);

        addTableHeader(deductionsTable, "DEDUCTIONS", boldFont);
        addTableRow(deductionsTable, "PF", payroll.getPfEmployee());
        addTableRow(deductionsTable, "Professional Tax", payroll.getProfessionalTax());
        addTableRow(deductionsTable, "Income Tax", payroll.getTaxDeductions());
        addTableRow(deductionsTable, "Other Deductions", payroll.getOtherDeductions());
        addTableRow(deductionsTable, "Total Deductions", payroll.getTotalDeductions(), boldFont);

        document.add(deductionsTable);
        document.add(new Paragraph("\n"));

        Font netSalaryFont = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD);
        Paragraph netSalary = new Paragraph("Net Salary: Rs." + payroll.getNetSalary(), netSalaryFont);
        netSalary.setAlignment(Element.ALIGN_RIGHT);
        document.add(netSalary);

        document.close();
        return outputStream.toByteArray();
    }

    private void addTableHeader(PdfPTable table, String header, Font font) {
        PdfPCell cell = new PdfPCell(new Paragraph(header, font));
        cell.setColspan(2);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(cell);
    }

    private void addTableRow(PdfPTable table, String label, BigDecimal value) {
        table.addCell(label);
        table.addCell("Rs." + (value != null ? value.toString() : "0"));
    }

    private void addTableRow(PdfPTable table, String label, BigDecimal value, Font font) {
        PdfPCell labelCell = new PdfPCell(new Paragraph(label, font));
        PdfPCell valueCell = new PdfPCell(new Paragraph("Rs." + (value != null ? value.toString() : "0"), font));
        table.addCell(labelCell);
        table.addCell(valueCell);
    }

    private String buildLegacyPayslipPath(String payslipPath) {
        if (payslipPath == null || payslipPath.isBlank() || payslipPath.startsWith("/api/")) {
            return null;
        }
        return payslipPath;
    }

    private String buildPayslipFileName(PayrollHistory payroll) {
        String monthPart = payroll.getPayrollMonth() == null
                ? "payslip"
                : payroll.getPayrollMonth().format(DateTimeFormatter.ofPattern("yyyy_MM"));
        return "payslip_" + payroll.getUserId() + "_" + monthPart + ".pdf";
    }
}
